version: "3"

services:
  api:
    build: ./api/
    command: /wait-for-it.sh redis:6379 -- /wait-for-it.sh elastic:9200 -- /entrypoint.sh
    ports:
      - 8080:8080
    volumes:
      - ./api/:/api/
      - ./wait-for-it.sh:/wait-for-it.sh
  redis:
    image: redis:3
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
